/*

insert license info here

*/

using System;

namespace Cuyahoga.Modules.ECommerce.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the Serdar's NHibernate Object Mapping 1.1 template (based on Gustavo's) - serdar@argelab.net
	/// </summary>
	[Serializable]
	public class Country 
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private string _countrycode; 
		private string _countryname; 
		private CurrencyInfo _defaultcurrencycode; 
		private DateTime _inserttimestamp; 
		private DateTime _updatetimestamp; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Country()
		{
			_countrycode = null; 
			_countryname = null; 
			_defaultcurrencycode =  null;
            _inserttimestamp = DateTime.Now;
            _updatetimestamp = DateTime.Now; 
		}

        public Country(string countryCode, string countryName) {
            _countrycode = countryCode;
            _countryname = countryName; 
        }
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Internal Accessors for NHibernate
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual string _CountryCode
		{
			get { return _countrycode; }
			set { _countrycode = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual string _CountryName
		{
			get { return _countryname; }
			set { _countryname = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual CurrencyInfo _DefaultCurrencyCode
		{
			get { return _defaultcurrencycode; }
			set { _defaultcurrencycode = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual DateTime _Inserttimestamp
		{
			get { return _inserttimestamp; }
			set { _inserttimestamp = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual DateTime _Updatetimestamp
		{
			get { return _updatetimestamp; }
			set { _updatetimestamp = value; }
		}
		
		#endregion // Internal Accessors for NHibernate 

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual string CountryCode
		{
			get { return _countrycode; }
			set	
			{
				if ( value != null )
					if( value.Length > 2)
						throw new ArgumentOutOfRangeException("Invalid value for CountryCode", value, value.ToString());
				
				_isChanged |= (_countrycode != value); _countrycode = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual string CountryName
		{
			get { return _countryname; }
			set	
			{
				if ( value != null )
					if( value.Length > 128)
						throw new ArgumentOutOfRangeException("Invalid value for CountryName", value, value.ToString());
				
				_isChanged |= (_countryname != value); _countryname = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual CurrencyInfo DefaultCurrencyCode
		{
			get { return _defaultcurrencycode; }
			set { _isChanged |= (_defaultcurrencycode != value); _defaultcurrencycode = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual DateTime Inserttimestamp
		{
			get { return _inserttimestamp; }
			set { _isChanged |= (_inserttimestamp != value); _inserttimestamp = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual DateTime Updatetimestamp
		{
			get { return _updatetimestamp; }
			set { _isChanged |= (_updatetimestamp != value); _updatetimestamp = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		
		#endregion
		
		
		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Country castObj = (Country)obj; 
			return ( castObj != null ) &&
				( this._countrycode == castObj.CountryCode );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * _countrycode.GetHashCode();
			return hash; 
		}
		#endregion
		
	}
}
