

using System;

namespace Cuyahoga.Modules.ECommerce.Domain {
    /// <summary>
    ///	Generated by MyGeneration using the Serdar's NHibernate Object Mapping 1.1 template (based on Gustavo's) - serdar@argelab.net
    /// </summary>
    [Serializable]
    public class DocumentType {
        #region Private Members
        private bool _isChanged;
        private bool _isDeleted;
        private int _typeid;
        private string _typename;
        private string _cssclass;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public DocumentType() {
            _typeid = 0;
            _typename = null;
            _cssclass = null;
          
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Internal Accessors for NHibernate

        /// <summary>
        /// 
        /// </summary>
        protected internal virtual string _CssClass {
            get { return _cssclass; }
            set { _cssclass = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected internal virtual string _TypeName {
            get { return _typename; }
            set { _typename = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected internal virtual int _TypeID {
            get { return _typeid; }
            set { _typeid = value; }
        }


        #endregion // Internal Accessors for NHibernate

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		
        public virtual string TypeName {
            get { return _typename; }
            set {
                if (value != null)
                   

                _isChanged |= (_typename != value); _typename = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public virtual int TypeID {
            get { return _TypeID; }
            set {

                _isChanged |= (_typeid != value); _typeid = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public virtual string CssClass {
            get { return _cssclass; }
            set { _isChanged |= (_cssclass != value); _cssclass = value; }
        }



        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsChanged {
            get { return _isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsDeleted {
            get { return _isDeleted; }
        }

        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public virtual void MarkAsDeleted() {
            _isDeleted = true;
            _isChanged = true;
        }


        #endregion


        #region Equals And HashCode Overrides
        /// <summary>
        /// local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals(object obj) {
            if (this == obj) return true;
            if ((obj == null) || (obj.GetType() != this.GetType())) return false;
            DocumentType castObj = (DocumentType)obj;
            return (castObj != null) &&
                (this._TypeID == castObj.TypeID);
        }

        /// <summary>
        /// local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode() {

            int hash = 57;
            hash = 27 * hash * _typeid.GetHashCode();
            return hash;
        }
        #endregion

    }
}
