using System;

namespace Cuyahoga.Modules.ECommerce.Domain {

    /// <summary>
    ///	Generated by MyGeneration using the Serdar's NHibernate Object Mapping 1.1 template (based on Gustavo's) - serdar@argelab.net
    /// </summary>
    [Serializable]
    public class ProductCategory {
    
        public const short SORT_ORDER_MIN = 1;

        #region Private Members
        private bool _isChanged;
        private bool _isDeleted;
        private long _categoryid;
        private long _productid;
        private Product _product;
        private short _sortorder;
        private DateTime _inserttimestamp;
        private DateTime _updatetimestamp;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public ProductCategory() {
            _categoryid = 0;
            _productid = 0;
            _sortorder = 0;
            _inserttimestamp = DateTime.Now;
            _updatetimestamp = DateTime.Now;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Internal Accessors for NHibernate

        /// <summary>
        /// 
        /// </summary>
        internal virtual long _Categoryid {
            get { return _categoryid; }
            set { _categoryid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        internal virtual long _Productid {
            get { return _productid; }
            set { _productid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        internal virtual short _SortOrder {
            get { return _sortorder; }
            set { _sortorder = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        internal virtual DateTime _Inserttimestamp {
            get { return _inserttimestamp; }
            set { _inserttimestamp = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        internal virtual DateTime _Updatetimestamp {
            get { return _updatetimestamp; }
            set { _updatetimestamp = value; }
        }

        #endregion // Internal Accessors for NHibernate

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		
        public virtual long CategoryID {
            get { return _categoryid; }
            set { _isChanged |= (_categoryid != value); _categoryid = value; }
        }

        public virtual Product Product {
            get { return _product; }
            set { _isChanged |= (_product != value); _product = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public virtual long ProductID {
            get { return _productid; }
            set { _isChanged |= (_productid != value); _productid = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public virtual short SortOrder {
            get { return _sortorder; }
            set { _isChanged |= (_sortorder != value); _sortorder = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public virtual DateTime Inserttimestamp {
            get { return _inserttimestamp; }
            set { _isChanged |= (_inserttimestamp != value); _inserttimestamp = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public virtual DateTime Updatetimestamp {
            get { return _updatetimestamp; }
            set { _isChanged |= (_updatetimestamp != value); _updatetimestamp = value; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsChanged {
            get { return _isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsDeleted {
            get { return _isDeleted; }
        }

        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public virtual void MarkAsDeleted() {
            _isDeleted = true;
            _isChanged = true;
        }


        #endregion


        #region Equals And HashCode Overrides
        /// <summary>
        /// local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals(object obj) {
            if (this == obj) return true;
            if ((obj == null) || (obj.GetType() != this.GetType())) return false;
            ProductCategory castObj = (ProductCategory)obj;
            return (castObj != null) &&
                (this._categoryid == castObj.CategoryID) &&
                (this._productid == castObj.ProductID);
        }

        /// <summary>
        /// local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode() {

            int hash = 57;
            hash = 27 * hash * _categoryid.GetHashCode();
            hash = 27 * hash * _productid.GetHashCode();
            return hash;
        }
        #endregion

    }
}