/*

insert license info here

*/

using System;

namespace Cuyahoga.Modules.ECommerce.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the Serdar's NHibernate Object Mapping 1.1 template (based on Gustavo's) - serdar@argelab.net
	/// </summary>
	[Serializable]
	public class State 
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private short _stateid; 
		private Country _countrycode; 
		private string _statecode; 
		private string _statename; 
		private DateTime _inserttimestamp; 
		private DateTime _updatetimestamp; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public State()
		{
			_stateid = 0; 
			_countrycode =  null; 
			_statecode = null; 
			_statename = null; 
			_inserttimestamp = DateTime.Now; 
			_updatetimestamp = DateTime.Now; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Internal Accessors for NHibernate
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual short _Stateid
		{
			get { return _stateid; }
			set { _stateid = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual Country _CountryCode
		{
			get { return _countrycode; }
			set { _countrycode = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual string _StateCode
		{
			get { return _statecode; }
			set { _statecode = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual string _StateName
		{
			get { return _statename; }
			set { _statename = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual DateTime _Inserttimestamp
		{
			get { return _inserttimestamp; }
			set { _inserttimestamp = value; }
		}
		
		/// <summary>
		/// 
		/// </summary>
		internal virtual DateTime _Updatetimestamp
		{
			get { return _updatetimestamp; }
			set { _updatetimestamp = value; }
		}
		
		#endregion // Internal Accessors for NHibernate 

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual short Stateid
		{
			get { return _stateid; }
			set { _isChanged |= (_stateid != value); _stateid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual Country CountryCode
		{
			get { return _countrycode; }
			set { _isChanged |= (_countrycode != value); _countrycode = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual string StateCode
		{
			get { return _statecode; }
			set	
			{
				if ( value != null )
					if( value.Length > 12)
						throw new ArgumentOutOfRangeException("Invalid value for StateCode", value, value.ToString());
				
				_isChanged |= (_statecode != value); _statecode = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual string StateName
		{
			get { return _statename; }
			set	
			{
				if ( value != null )
					if( value.Length > 128)
						throw new ArgumentOutOfRangeException("Invalid value for StateName", value, value.ToString());
				
				_isChanged |= (_statename != value); _statename = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual DateTime Inserttimestamp
		{
			get { return _inserttimestamp; }
			set { _isChanged |= (_inserttimestamp != value); _inserttimestamp = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual DateTime Updatetimestamp
		{
			get { return _updatetimestamp; }
			set { _isChanged |= (_updatetimestamp != value); _updatetimestamp = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		
		#endregion
		
		
		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			State castObj = (State)obj; 
			return ( castObj != null ) &&
				( this._stateid == castObj.Stateid );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * _stateid.GetHashCode();
			return hash; 
		}
		#endregion
		
	}
}
